version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:

      - aws codeartifact login --tool npm --repository milkman --domain milkmantechnologies --namespace @milkman --domain-owner 263652615682

      - npm install
      - npm test 
      - npm run bundle
      - npm publish
