version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:
      - .ci/verify_version_deployability.sh

      - npm install
      - npm test 

      - echo "Test passed and version is ok"
      - echo "Finished successfully"
